#THIS INFO SHOULD NEVER BE COMMITTED TO GITHUB
#COPY THIS FILE TO stripe.rb (WHICH IS IN .gitignore) AND THEN IN stripe.rb
#PUT YOUR STRIPE API KEY INFO HERE AND UNCOMMENT THE TWO LINES BELOW:

#Stripe.api_key = "sk_SECRET_KEY"
#STRIPE_PUBLIC_KEY = "pk_PUBLIC_KEY"
